import { HomePage } from "@/components/homepage";
import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // if (data) return console.log(data);
  return (
    <div className={inter.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className="text-sm italic my-2 text-slate-500 font-light">
          Retreived anime
        </p>
        <h1 className="text-5xl text-center mb-7 font-black">アニメ一覧</h1>
        <HomePage />
      </main>
    </div>
  );
}
