import { HomePage } from "@/components/homepage";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // if (data) return console.log(data);
  return (
    <div className={inter.className}>
      <Head>
        <title>GraphQL Fetch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="my-2 text-sm italic font-light text-center text-slate-500">
          Retreived anime
        </p>
        <h1 className="text-5xl font-black text-center mb-7">アニメ一覧</h1>
        <HomePage />
      </main>
    </div>
  );
}
